# __Computing on Data__

In [1]:
A = [1 2; 3 4; 5 6] % 3x2 matrix

A =

   1   2
   3   4
   5   6



In [2]:
B = [11 12; 13 14; 15 16] % 3x2 matrix

B =

   11   12
   13   14
   15   16



In [3]:
C = [1 1; 2 2] % 2x2 matrix

C =

   1   1
   2   2



In [4]:
A*C

ans =

    5    5
   11   11
   17   17



In [5]:
A .* B % each element of A times each of the B elements

ans =

   11   24
   39   56
   75   96



In [6]:
A .^ 2 % element wide squaring fo A

ans =

    1    4
    9   16
   25   36



In [7]:
v = [1; 2; 3]

v =

   1
   2
   3



In [8]:
1 ./ v

ans =

   1.0000
   0.5000
   0.3333



In [9]:
1 ./ A

ans =

   1.0000   0.5000
   0.3333   0.2500
   0.2000   0.1667



In [10]:
log(v)

ans =

        0
   0.6931
   1.0986



In [11]:
exp(v)

ans =

    2.7183
    7.3891
   20.0855



In [12]:
v

v =

   1
   2
   3



In [14]:
abs([-1; -2; -3])

ans =

   1
   2
   3



In [15]:
-v % same as -1 * v

ans =

  -1
  -2
  -3



In [16]:
v + ones(length(v), 1) % adding one for each v element

ans =

   2
   3
   4



In [17]:
v .+ 1 % adding one for each v element

ans =

   2
   3
   4



In [18]:
v+1 % also adds one for each v element

ans =

   2
   3
   4



In [19]:
A

A =

   1   2
   3   4
   5   6



In [20]:
A' % transpose of A

ans =

   1   3   5
   2   4   6



In [22]:
(A')'

ans =

   1   2
   3   4
   5   6



In [23]:
a = [1 15 2 0.5]

a =

    1.0000   15.0000    2.0000    0.5000



In [24]:
val = max(a) % returns the maximum value of 'a'

val = 15


In [25]:
[val, ind] = max(a) % returns the maximum value of 'a' and its respective index

val = 15
ind = 2


In [26]:
max(A) % column wide maximum

ans =

   5   6



In [27]:
a < 3 % wide element comparisson (0 -false; 1 - true)

ans =

  1  0  1  1



In [28]:
find(a < 3)

ans =

   1   3   4



In [29]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [30]:
[r, c] = find(A >= 7)

r =

   1
   3
   2

c =

   1
   2
   3



In [31]:
A(2,3)

ans = 7


In [36]:
a

a =

    1.0000   15.0000    2.0000    0.5000



In [38]:
sum(a)

ans = 18.500


In [39]:
prod(a)

ans = 15


In [40]:
floor(a) % rounded

ans =

    1   15    2    0



In [41]:
ceil(a) % rounded

ans =

    1   15    2    1



In [42]:
rand(3)

ans =

   0.022888   0.354821   0.011674
   0.490198   0.327201   0.351538
   0.538751   0.705797   0.974667



In [43]:
max(rand(3), rand(3))

ans =

   0.9595   0.6052   0.9567
   0.8116   0.9107   0.2049
   0.5822   0.9838   0.5282



In [44]:
A

A =

   8   1   6
   3   5   7
   4   9   2



In [46]:
max(A, [], 1)

ans =

   8   9   7



In [47]:
max(A, [], 2)

ans =

   8
   7
   9



In [48]:
max(max(A))

ans = 9


In [49]:
max(A(:))

ans = 9


In [50]:
A = magic(9)

A =

   47   58   69   80    1   12   23   34   45
   57   68   79    9   11   22   33   44   46
   67   78    8   10   21   32   43   54   56
   77    7   18   20   31   42   53   55   66
    6   17   19   30   41   52   63   65   76
   16   27   29   40   51   62   64   75    5
   26   28   39   50   61   72   74    4   15
   36   38   49   60   71   73    3   14   25
   37   48   59   70   81    2   13   24   35



In [51]:
sum(A, 1) % column wide sum 

ans =

   369   369   369   369   369   369   369   369   369



In [52]:
sum(A, 2) % row wide sum

ans =

   369
   369
   369
   369
   369
   369
   369
   369
   369



In [53]:
eye(9)

ans =

Diagonal Matrix

   1   0   0   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   0   0   1



In [54]:
A .* eye(9)

ans =

   47    0    0    0    0    0    0    0    0
    0   68    0    0    0    0    0    0    0
    0    0    8    0    0    0    0    0    0
    0    0    0   20    0    0    0    0    0
    0    0    0    0   41    0    0    0    0
    0    0    0    0    0   62    0    0    0
    0    0    0    0    0    0   74    0    0
    0    0    0    0    0    0    0   14    0
    0    0    0    0    0    0    0    0   35



In [55]:
sum(A.*eye(9))

ans =

   47   68    8   20   41   62   74   14   35



In [56]:
sum(sum(A.*eye(9)))

ans = 369


In [57]:
flipud(A.*eye(9)) % flips de matrix

ans =

    0    0    0    0    0    0    0    0   35
    0    0    0    0    0    0    0   14    0
    0    0    0    0    0    0   74    0    0
    0    0    0    0    0   62    0    0    0
    0    0    0    0   41    0    0    0    0
    0    0    0   20    0    0    0    0    0
    0    0    8    0    0    0    0    0    0
    0   68    0    0    0    0    0    0    0
   47    0    0    0    0    0    0    0    0



In [59]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [61]:
pinv(A) % the inverse of A

ans =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778



In [64]:
temp = pinv(A)

temp =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778



In [69]:
temp*A % identity matrix do A

ans =

   1.0000e+00   8.3267e-17  -2.9698e-15
  -5.9952e-15   1.0000e+00   6.3838e-15
   2.9421e-15   4.4409e-16   1.0000e+00

